services:
#  backend:
#    build: .
#    depends_on:
#      - postgres
#    ports:
#      - '8080:8080'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=client'
    ports:
      - '5432:5432'

